### ISSUE TITLE
Valve status (Percentage )

### ISSUE THREAD

**Issue by max-rh** [Tomas-Mrazek/SmartThings#2]
Hi Tomas, 
I would like to start by thanking for an amazing job on this DH, we have already tried multiple DH for Fibaro Heat controller and yours by far is the best and the most stable one.

I just have few issues/clarifications that i need some help with if you don't mind:
 1- Is there a way to know how much the valve is open in percentage?, i know someone might estimate that based on the color and temperature, but is there a way to get the actual status of the valve?
 2- what does the default schedule (240 min) does ?
 3- And what is the difference between the window open mode and the fast window open mode ?

just an extra note regarding the UX, its quite good but my last two tile (Firmaware and Device) are not updating (they are empty), is this a know bug?

Thanks

**Comment by Tomas-Mrazek** [comment]
Thank you!

1) Unfortunately no. The device itself cannot allow that. It's actually quite a frequent request on Fibaro forums to allow that. You can read more [here](https://forum.fibaro.com/topic/28266-how-much-the-valve-is-open-fibaro-heat-controller/).
2) Scheduling itself is a way to set up well... schedule directly in the device. For example, you can set that temperature should be 20 degrees on weekends, 21 on weekdays between 8:00 and 21:00. If you have this setup and change radiator temperature manually during a weekend to 24 degrees, that's the overriding schedule. The parameter specified in settings just means, how long should the override schedule be active. After the time passes, temperature goes back to scheduled one. Scheduling itself is not implemented. It's beyond SmartThings capabilities for DH and I would have to create SmartApp for it.
3) Honestly, I don't know. I recently asked on Fibaro forums and not even the guy, who has the most knowledge about TRVs didn't know. There are two possible functions for "Open Window Detector". It either detects fast drops in temperature, thus signaling open window or it fires signal only when the temperature drops below zero degrees (this assumption is based on the main Fibaro site). Both the guy from the forum and I run few tests with the external sensor inside a freezer and opening window during cold days and none of us actually managed to fire that signal. It might not even work now or it ignores the temperature from the external sensor.

About firmware, Fibaro does not allow to update their firmware by other means than with their specific Z-Wave controller – which is also triple the price of SmartThings. I absolutely hate this decision and you're welcome to write them an email about how this decision is stupid because the older firmware is buggy, broken and autoregulation is not good. SmarThings developers are working on OTA firmware updates, so it would be great if we were able to update it. Anyway, those three buttons just print z-wave device and firmware info to logger inside developer workspace. Version button is the correct one if you want to know, what firmware version do you have. Possible values are 4.0, 4.3 and 4.4. From what I read on forums 4.0 and 4.3 are not good. 4.5 version should be soon available. You can update it via Fibaro Home Center controller or via your retail shop. If my shop won't update my TRVs I'm going to send it to RMA. They will send it to Fibaro service and they will update it.

**Comment by max-rh** [comment]
Hi Tomas,

Thank you so much for the clarifications. We are currently looking for a way to update the Firmware on the devices (we dont have a retail shop in our region) so it looks like we have to ship the devices back for such a thing.

I have another question if you dont mind, we are experiencing an issue with multiple devices were when you set the mode to auto and the temperature gets higher than the set point, the valve seems to stay fully open and vice versa ( when the temperature gets below the set point the valve stays closed), we tried resetting and re calibrating with no luck. is this a known issue ?

**Comment by Tomas-Mrazek** [comment]
I have a similar problem. I bet that this issue is due to bad algorithm inside the device. As I said, firmware 4.0 and 4.3 are broken, 4.4 should fix the heating algorithm.

**Comment by max-rh** [comment]
Hi Tomas,

Sorry for the late reply, thanks so much for the clarification.
To your knowledge, is there a workaround to update the devices firmware manually without the use of a fibaro hub; because unfortunately we are not in the same region as fibaro, and sending them back is kinda expensive, any advice ?

**Comment by Tomas-Mrazek** [comment]
There is not, as far as I know. I don't know, where you live, but in Europe, we're able to RMA items in both manufacturer and retail shop.

**Comment by max-rh** [comment]
Hi Tomas,
Hope your doing well...Merry Christmas
We finally got a few Fibaro heat controllers with the latest firmware "4.4", we have been using them for a while now, but still we have some weird behavior on some of them, i was wondering if you can advice regarding this; we have been monitoring and analyzing them using a database and grafana:

"Black line is set temperature and green is the actual temperature"

as you can see from the following graphs:
![image](https://user-images.githubusercontent.com/25219094/50400876-0e1ed780-0793-11e9-8d4f-7953133e1458.png)

![image](https://user-images.githubusercontent.com/25219094/50400888-36a6d180-0793-11e9-9805-5d709dbc7d55.png)

As you can see, the heat controllers sometimes stays fully on even if the temperature is higher than the set temperature or when we get the set point lower .

Thanks alot for your response and support.

**Comment by Tomas-Mrazek** [comment]
Hi, happy holidays to you!

Well, that's disappointing. I thought that 4.4 is a finally good firmware. You said you're experiencing issues with only few of them or with all of them? That's quite relevant information. Also are you using external sensor? Is your data based on this sensor? Where was it placed?

There might be an error in device handler, but without further data I'm afraid I cannot help you. More data would be appreciated in any way. I wonder what the graph looks for working device. Anyway I can suggest to register on official Fibaro forum and create a thread / talk to petergebruers, he has a lot of info.
